### ISSUE TITLE
I also wrote an implementation

### ISSUE THREAD

**Issue by quickdudley** [catseye/SICKBAY#1]
This probably doesn't belong in issues, but Github doesn't have general comments.

Today I wrote a SICKBAY interpreter in Haskell and uploaded it to github gists [here](https://gist.github.com/quickdudley/51660f98be16653682cf9a8249a57dcb)

**Comment by cpressey** [comment]
> Today I wrote a SICKBAY interpreter in Haskell and uploaded it to github gists here

That's great!  I've added a link to the README.

For the record, another good place to note these sorts of things, is on the esowiki article for the esolang in question. I've added it to the External Resources section of https://esolangs.org/wiki/SICKBAY .
